# Generated by Django 3.2.6 on 2025-04-21 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Resume', '0002_auto_20250419_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdetails',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='basic_details', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certifications',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experince',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='startdate',
            field=models.DateField(),
        ),
    ]
