# Generated by Django 3.2.6 on 2025-04-22 06:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Resume', '0003_auto_20250421_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('startdate', models.DateField(default=datetime.date.today)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('location_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills_used', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='certifications',
            name='certificate_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='certifications',
            name='certification_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='course_duration',
            field=models.PositiveIntegerField(help_text='Duration in months or years'),
        ),
        migrations.DeleteModel(
            name='Experince',
        ),
    ]
