# Generated by Django 3.2.6 on 2025-04-22 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_auto_20250422_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2025, 4, 22, 12, 5, 3, 482855)),
        ),
    ]
