# Generated by Django 3.2.6 on 2025-04-22 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0005_alter_experience_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2025, 4, 22, 12, 6, 51, 753875)),
        ),
    ]
