# Generated by Django 3.2.6 on 2025-04-22 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0007_alter_experience_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2025, 4, 22, 13, 14, 11, 430703)),
        ),
    ]
