# Generated by Django 3.2.6 on 2025-04-24 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0008_alter_experience_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2025, 4, 24, 13, 3, 1, 973753)),
        ),
        migrations.AddField(
            model_name='education',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2025, 4, 24, 13, 3, 1, 973753)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2025, 4, 24, 13, 3, 1, 973753)),
        ),
        migrations.AlterField(
            model_name='project',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2025, 4, 24, 13, 3, 1, 973753)),
        ),
    ]
