# Generated by Django 3.2.6 on 2025-04-29 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0009_auto_20250424_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2025, 4, 29, 17, 53, 6, 260436)),
        ),
        migrations.AlterField(
            model_name='education',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2025, 4, 29, 17, 53, 6, 260436)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2025, 4, 29, 17, 53, 6, 260436)),
        ),
        migrations.AlterField(
            model_name='project',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2025, 4, 29, 17, 53, 6, 260436)),
        ),
    ]
